### ISSUE TITLE
learn booleans

### ISSUE THREAD

**Issue by Semus08** [Semus08/Basic-programming#1]
## Description
this is to learn ihow if statements work because it works on a true or false principle

### TASKS
 - [x] create bool variable
 - [x] make if statement
 - [x] print if true or false
