### ISSUE TITLE
Usage of array

### ISSUE THREAD

**Issue by jiri132** [Semus08/Basic-programming#2]
## Description
Make an variable array to do this you need to use the syntax [ ] (syntax is how you type something in code)
<TYPE>[] <NAME> 
for example int[] rowan;

### Task
- [ ] make a new function called ARRAYS
- [ ] make an int array
- [ ] make an float array
- [ ] give values to the arrays 
- [ ] if you can't get further than decalring the arays search on google the syntax NO YOUTUBE!
